version: "3.9"
services:
  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=alexdemichieli
      - POSTGRES_USER=alexdemichieli
      - POSTGRES_PASSWORD=alex
    networks:
      - db-net
    volumes:
    - .db:/var/lib/postgresql/data/
    
  project:
    restart: always
    container_name: code
    command : bash -c "python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:9000"
    # env_file:
    #   - ./project/settings.ini
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - db-net

  frontend:
    restart: always
    command : npm start
    container_name: front
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - project
    networks:
      - db-net

networks:
  db-net:
    driver: bridge
# version: '3.9'
# services:
#   backend:
#     build:
#       context: ./server/
#       dockerfile: Dockerfile
#     command: 'python manage.py runserver 0.0.0.0:9000'
#     ports:
#       - 9000:9000
#     volumes:
#       - .:/app
#     depends_on:
#       - db

#   db:
#     image: postgres:13.0-alpine
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#       - POSTGRES_USER=hello_django
#       - POSTGRES_PASSWORD=hello_django
#       - POSTGRES_DB=hello_django_dev

# volumes:
#   postgres_data: