version: '3.9'

services:
  backend:
    build: ./backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/backend/staticfiles
    expose:
      - 8000:8000
    env_file:
      - ./.env 
    depends_on:
      - db
  # frontend:
  #   build: ./client
  #   volumes:
  #     - react_build:/react/build
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
        POSTGRES_PASSWORD: postgres
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/backend/staticfiles
      # - react_build:/var/www/react
    ports:
      - 1337:80
    depends_on:
      - backend
      # - frontend

volumes:
  postgres_data:
  static_volume:
  # react_build:
